"""adujst decisions table parameter

Revision ID: fa26ba353c05
Revises: 57aad68705bc
Create Date: 2025-12-24 10:53:57.916709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from repositories.db.init import JSONField
# revision identifiers, used by Alembic.
revision: str = 'fa26ba353c05'
down_revision: Union[str, Sequence[str], None] = '57aad68705bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('feature_id', sa.String(length=64), nullable=False, comment='Feature id'))
    op.add_column('decisions', sa.Column('feature_key', sa.String(length=128), nullable=False, comment='Feature key'))
    op.add_column('decisions', sa.Column('variant_key', sa.String(length=64), nullable=False, comment='Variant key'))
    op.add_column('decisions', sa.Column('variant_payload', JSONField(), nullable=False, comment='Variant payload JSON'))
    op.create_index(op.f('ix_decisions_feature_id'), 'decisions', ['feature_id'], unique=False)
    op.create_index(op.f('ix_decisions_feature_key'), 'decisions', ['feature_key'], unique=False)
    op.create_foreign_key('fk_feature_active_experiment', 'features', 'experiments', ['active_experiment_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_feature_active_experiment', 'features', type_='foreignkey')
    op.drop_index(op.f('ix_decisions_feature_key'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_feature_id'), table_name='decisions')
    op.drop_column('decisions', 'variant_payload')
    op.drop_column('decisions', 'variant_key')
    op.drop_column('decisions', 'feature_key')
    op.drop_column('decisions', 'feature_id')
    # ### end Alembic commands ###
